name: Debug

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dump:
    name: Dump
    runs-on: windows-latest
    steps:
      - name: Debug
        env:
          GITHUB: "${{ toJSON(github) }}"
        run: echo "${GITHUB}"
